### ISSUE TITLE
Wifi no work 

### ISSUE THREAD

**Issue by lodarmayarder** [PhoenixPE/PhoenixPE#6] opened 2022-07-29 06:11 UTC
﻿

Checklist
---------
- [X] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------

Build from Winre, iso Win10 2004.
The wifi adapter is recognized, the wifi does not work, the Wlansvc service from PEnetwork returns error 1075 and does not want to start.
Attempt to start from command line does not work, nor from services.msc with the same error encountered.

**Comment by homes32** [comment] 2022-07-31 13:36
Thank you for reporting. I have reproduced this error on one of my test systems.

**Comment by homes32** [comment] 2022-07-31 16:25
Fixed in https://github.com/PhoenixPE/PhoenixPE/commit/9b02651cca8505a1c59017d92c41d332e5ec757f

The issues was caused by the WlanSvc service dependencies being written as a single comma separated string instead of a null terminated list.

**Comment by lodarmayarder** [comment] 2022-08-01 11:35
Ca fonctionne, merci ! J'ai une suggestion, pourquoi ne pas se simplifier la tache en utilisant PortableApps.com pour intégrer dans un premier temps certains logiciels en USB ? 
Définir ainsi le repertoire d'installation des programmes non rams en Y:/PortableApps ? 
Par la suite envisager de passer par PortableApps pour configurer les applications avant de lancer la construction et de l'intégrer en ram ? 
Merci pour le travail

**Comment by lodarmayarder** [comment] 2022-08-01 11:36
It works, thank you! 
I have a suggestion, why not simplify the task by using PortableApps.com to first integrate some software in USB?
In this case, set the installation directory for non ram programs to Y:/PortableApps?
Then consider going through PortableApps to configure the applications before launching the construction and integrating it in ram?
Thanks for the work !! ;)

**Closed** 2022-08-17 02:43 UTC
Labels: bug
