### ISSUE TITLE
Notepad++ / Notepad3: "A specified logon session does not exist. it may already have been terminated."

### ISSUE THREAD

**Issue by ElektroStudios** [PhoenixPE/PhoenixPE#45] opened 2023-04-28 11:56 UTC
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
Issue urgency: high

Win10 source: Windows 10 2004 (10.0.19041.264) EN
PhoenixPE project settings: minimal, almost default.

**Problem description**
In certain circumstances, **Notepad++** and **Notepad3** scripts are preventing from being able to open / read text files (.txt, .ini, etc) by causing this error message:

![](https://i.imgur.com/DnNQJeI.png)

If I remember good (because when I first tried to track the source of this problem it was two days ago while testing for first time PhoenixPE) this issue also affected to the behavior of other parts of the OS when dealing with the control panel applets or other things, but I don't remember exactly what.

For this reason the issue it seems to be very problematic, not only for preventing to open plain text files.

------------------------------

**To Reproduce**
Step-by-step instructions on how to reproduce the behavior:

There are two similar ways that I found to get to the same error.

First way:
 - Enabling the "Set as default text editor" option in the **Notepad++** script settings page.

Second way: 
 - Enabling the **Notepad3** script component and letting its settings as default.

---------------------------------

1. Download and run **PEBakeryLauncher.exe** from **PhoenixPE** release ("PhoenixPE-2023.03.28-64.zip").

Now, to reproduce first mentioned way:
2a. In the project tree, go to **Applications -> Productivity -> Notepad++** script, and check the "Set as default text editor" option:
![](https://i.imgur.com/YLkuwS1.png)

Or to reproduce second mentioned way:
2b. In the project tree, go to **Applications -> Productivity**, then uncheck "Notepad++" script and check "Notepad3" script:
![](https://i.imgur.com/YlwgIu3.png)

3. Build the project, load the **PhoenixPE** in a virtual machine (I've tested it in VMWare Player 17), and try to open a text file (.txt, .ini, etc).

**Comment by homes32** [comment] 2023-05-01 00:13
My free time has been limited, but this looks to be caused by runtime/dependencies with certain versions of notepad++ and notepad3.

With notepad++ I can reproduce with v 8.5.1 and the issue does not occur with v8.5.2. just for fun I tried and was able to reproduce the same issue in the Win10XPE project with the v8.5.1 version.

The set as default text editor option has nothing to do with the issue., and I also found a bug in notepad++'s file extension registration.

more investigation is needed but now that I have 2 versions of NPP to test with I should be able to narrow the issue down by looking at the commit logs.

**Comment by Whatslp** [comment] 2023-07-08 18:06
last working Version of Notepad3 is 5.21.227.1 release date 2021-02-27
https://github.com/rizonesoft/Notepad3/releases/download/RELEASE_5.21.227.1/Notepad3_5.21.227.1.zip
Notepad3 (x64) v5.21.227.1 (620dd685)
Compiler: MS Visual C++ 2019 v16.8.(5-6) (VC v1928)

starting with Notepad3 (x64) v5.21.905.1 - it is not working anymore

Notepad3 (x64) v5.21.905.1 (946e6b05)
Compiler: MS Visual C++ 2019 v16.11.(0-2) (VC v1929)

Notepad3 (x64) 6.23.203.2 (e108c574)
Compiler: MS Visual C++ 2022 v17.4.(3-4) (VC v1934)

Notepad++ v8.5.4 is working as well as v8.5.2

in both cases it is the same behavior in Win10XPE

**Comment by homes32** [comment] 2023-07-29 15:01
The issue was introduced when the `msix` (https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests#msix) attribute was introduced into the application manifest in both cases (notepad3 and notepad++). notepadd++ removed the attribute a release or so later, but notepad3 has not. If I modify the manifest manually with reshacker or recompile from source without the ```<msix xmlns="urn:schemas-microsoft-com:msix.v1" publisher="CN=Rizonesoft" packageName="RizonesoftNotepad3" applicationId="RizonesoftNotepad3"></msix>``` attribute the application works as expected.

**Comment by homes32** [comment] 2023-07-30 19:17
https://github.com/rizonesoft/Notepad3/issues/4949

**Comment by hpwamr** [comment] 2023-07-31 20:41
For Your Information: On Notepad3, the "msix" attributes are just commented out.
See: https://github.com/rizonesoft/Notepad3/issues/4949#issuecomment-1658885057

**Comment by ElektroStudios** [comment] 2023-07-31 20:47
I can't test it for a few months, so I let @homes32 do it (in case he can and want to do it) and to close this thread if it's solved.

Thank you all so much for your time and help.

**Comment by homes32** [comment] 2023-08-01 01:39
Issue resolved in Notepad3 build 6.23.731.1_rc

Will update script download URLs once the stable release is published.

**Closed** 2024-01-13 20:59 UTC
Labels: external
