### ISSUE TITLE
strange characters in menu

### ISSUE THREAD

**Issue by webmogul1** [PhoenixPE/PhoenixPE#8] opened 2022-08-26 23:12 UTC
﻿

Checklist
---------
- [X] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿

**Describe what is happening**
Any idea why are those characters showing in the menu of the resolution changer?

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/5225701/187001619-292afac5-0cc8-4eb0-b91b-6b03cde9546b.png)

**Comment by homes32** [comment] 2022-08-27 13:33
It's a bug with the way PECMD handles creating its own internal resolutions menu and hardcodes chinease characters. Have you modified the resource definitions for the menu or PECMD or is it behaving like this in a stock build? Its very sensitive to item placement when a submenu is present.

**Comment by webmogul1** [comment] 2022-08-27 17:59
nothing was changed

**Comment by homes32** [comment] 2022-08-29 17:43
looking at the screenshot you posted, PECMD "appears" to have been tampered with, as I can see your missing a divider line between Auto Resolution and Load Drivers, which is what is triggering the bug with the menu.
![PECMD Menu](https://user-images.githubusercontent.com/6519152/187263051-15f826d0-1b1e-4099-9697-50726d3785ee.png)

that or you have something weird going on with your environment that I can't reproduce in any of my test systems.

can you think of any other information or provide additional details on your build system, test system, build log, etc?
If you could also provide a MD5 or SHA-2 checksu;m of `Workbench\PhoenixPE\Target\Windows\System32\PECMD.exe` we can compare with the repository and determine if something is interfering (antivirus, etc.) with the exe during the build.

**Comment by webmogul1** [comment] 2022-08-29 19:37
MD5
`45d520bc6beda2e9da630e2b458fbaba *PECMD.EXE`
running on VirtualBox

**Comment by webmogul1** [comment] 2022-08-29 19:43
downloaded original script again and I am having the same issue.

**Comment by homes32** [comment] 2022-08-29 23:29
I was able to reproduce this using virtualbox. I'll mess around and see if I can work around the issue, but I'll probably have better luck in the long term finding a decent Chinese translator and trying to get the author to fix the bug.

**Comment by webmogul1** [comment] 2022-08-30 03:03
Maybe try another pecmd version?

**Comment by homes32** [comment] 2022-08-31 01:24
It affects all the versions released in the past couple years, and the versions older then that don't have the commands I need.

**Comment by Rolf185** [comment] 2023-03-19 08:06
I'm using PECMD.EXE (https://drive.google.com/file/d/1jPm6jYP8TARYrcKzr6tKv1tputu3I5iA/view?usp=sharing) version 1201.88.5.81 (MD5: 3cd19afec8868260d9d552b246ffc186). It was included in Win10XPE (2021-01-16). This version works fine.
Rolf

**Comment by homes32** [comment] 2024-01-06 00:53
Resolved in 1c17ec77c3b58693a3330a88d21a0db8a5b8e76f

**Closed by homes32** 2024-01-06 00:53 UTC
Labels: external
