### ISSUE TITLE
Network status icon not showing correct connection state

### ISSUE THREAD

**Issue by yellobyte** [PhoenixPE/PhoenixPE#56] opened 2023-08-15 15:08 UTC
﻿

Checklist
---------
- [ x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿

**Describe what is happening**
Even though a PC equipped with a multiple-port network card (e.g. Mellanox ConnectX-3) has proper network connection on one port the network status icon on the taskbar (bottom right) still shows a red cross (network error).

**To Reproduce**
As explained above.

**Expected behavior**
Network status icon ideally to show the state "network/internet ok".

**Screenshots/Logs**
attached
![PE NW Manager 01](https://github.com/PhoenixPE/PhoenixPE/assets/76921504/8a806c60-c633-4d2a-a8d2-ff6b0669ac77)
![PE NW Manager 02](https://github.com/PhoenixPE/PhoenixPE/assets/76921504/9997f978-0ce5-4e86-bbcd-5af9baebafc6)
![PE NW Manager 03](https://github.com/PhoenixPE/PhoenixPE/assets/76921504/1eef9d80-a574-4be5-a761-3dd30acdf4a2)

**Comment by homes32** [comment] 2023-08-17 01:46
are you able to post the PENetwork debug log from your PE? `B:\PENMDebug.txt`

PENetwork is a 3rd party application but I can see if the issue is easily reproducible or traceable.

**Comment by yellobyte** [comment] 2023-08-17 23:52
The requested file is attached.   BTW: The network card is a 2-port Mellanox MCX354A with LAN only connected to port 1.
[PENMDebug.txt](https://github.com/PhoenixPE/PhoenixPE/files/12374145/PENMDebug.txt)

**Comment by homes32** [comment] 2024-07-18 00:49
I'm going to close this as it's not directly related to or developed PhoenixPE (PEnetwork app), I can't reproduce it, and it seems to be isolated to an uncommon network card. Sorry.

**Closed by homes32** 2024-07-18 00:49 UTC
Labels: wontfix, external
