### ISSUE TITLE
Space in path causes PhoenixAPI-DriveGetType to fail

### ISSUE THREAD

**Issue by datacarecorp** [PhoenixPE/PhoenixPE#107] opened 2024-09-05 11:57 UTC
Dear Team 
Thank you for developing this wonderful project.
I am struggling since almost a month to create PE iso but all I am getting is errors & warnings.
I have tried many windows 10 /11 builds from latest to old but nothing is working.
Is there any way to get any simple working version.
Thank you

**Comment by homes32** [comment] 2024-09-06 02:30
>  Is there any way to get any simple working version. Thank you

You can start by following the instructions you ignored when you opened this ticket, and post the support log from the logs folder.

**Comment by datacarecorp** [comment] 2024-09-06 07:28
Hi home32 Good Morning
Thank you so much for your valuable support. Appreciate your technical expertise as a lead developer of the project.
I have tried it again , here are steps I followed -
1) I am using latest windows 11 ISO
2) Converted install.esd to install.win using github decrypter (esd-decrypter-wimlib-65)
3) Without any selection (except source folder selection) started build I wanted to customize actually)
Here are errors I am getting.
Pls. help. Thanks
download link -https://drive.google.com/file/d/1BWafCj9y0WbM09w9G__yEGTunVzTbXHC/view?usp=sharing

**Comment by homes32** [comment] 2024-09-08 00:57
What type of drive is your `G:\` drive where you have PhoenixPE?
The error occurs because Windows classifies it as unknown. If you can provide more details perhaps we can work around it.

**Comment by homes32** [comment] 2024-09-08 13:27
The issue is due to incorrect handling with the path with certain command when the project path contains spaces.

A fix will be available shortly. in the meantime if you want to work around the issue you can change your path to remove the space and the build should complete.

`G:\Download\winpe related\PhoenixPE-2024.08.17-x64`
to
`G:\Download\winpe-related\PhoenixPE-2024.08.17-x64`

**Comment by datacarecorp** [comment] 2024-09-10 06:18
Thank a ton homes32
I am eager to try solution , will update you results. Thanks again

**Comment by datacarecorp** [comment] 2024-09-10 06:39
Hi homes32
I have changed project path to root & one error was removed. I am getting 2 other errors but I think they are minor (error in line 154 & 234) .Here is full log -
![err2](https://github.com/user-attachments/assets/3a61afdd-0d19-423d-a6de-2cba8d6d02ab)
![error1](https://github.com/user-attachments/assets/d833120f-cb7c-4bb4-bdff-3e25c2a913b5)
![error13](https://github.com/user-attachments/assets/eddac4d3-aca8-41e8-8a43-4668d7781386)
[BuildLog_2024_09_09_233046_Project_PhoenixPE.txt](https://github.com/user-attachments/files/16940548/BuildLog_2024_09_09_233046_Project_PhoenixPE.txt)

**Comment by homes32** [comment] 2024-09-12 01:08
The Compress error was fixed in a previous commit, but its not part of the project build so it can be ignored for now.

` [Error] WimExtract - [PathDoesNotExist] [ERROR] Path "Windows\System32\Recovery\WinRE.wim" does not exist in WIM image 2 (WimExtract,%SourceInstallWim%,%SourceInstallWimImage%,Windows\System32\Recovery\WinRE.wim,%ProjectCache%,NOACL) (Line 152)`

Shows that we are unable to extract WinRE.wim from your source. This makes sense, as you have your 'install.wim' image set incorrectly on the Config Source script. `[Success] Local variable [%cmb_SrcInstallImage%] set to [2 - Microsoft Windows Setup (amd64)]` 

You need to use Windows 11 Pro as the image. Microsoft Windows Setup won't work as it doesn't contain the needed files.
Change the image. If there isn't another image then you need to find a different source as the .esd converted sources don't always have everything. It's always best to use full install ISO if possible.

**Comment by datacarecorp** [comment] 2024-09-12 08:05
Thank You so much I will let program to download windows ISO.

**Comment by datacarecorp** [comment] 2024-09-12 12:23
Hi homes32
Thanks for your help finally I have got success with project. I have downloaded windows iso from uudump & it worked.
I have not customized PE yet but I am sure It will work with full selection of apps as well.
Only one error was encountered attached is snapshot for your ref.
Thanks again.
![1](https://github.com/user-attachments/assets/e44d25dc-0726-4ff6-88af-dcdb79ccec62)
![2](https://github.com/user-attachments/assets/84ebc797-32cf-40f0-b914-d7b3e36d2460)
[BuildLog_2024_09_12_163457_Project_PhoenixPE.txt](https://github.com/user-attachments/files/16979107/BuildLog_2024_09_12_163457_Project_PhoenixPE.txt)

**Comment by datacarecorp** [comment] 2024-09-13 00:32
Good Morning homes32 & Team
With little struggle I have been successful in making my customised PE ( wallpaper & program selection for Data Recovery & diagnostics)
Attached is log for your ref & future builds. Only line 234 is having error now.
HWinfo is having download issue which halted earlier build . I have removed all networking components & intel driver support.
Thank you for developing this wonderful project.
![1](https://github.com/user-attachments/assets/7fb2ace4-5cb9-4171-9db1-2a289a68dd7a)
![2](https://github.com/user-attachments/assets/686a9882-d096-49db-8b41-1748ddacf4e3)
![3](https://github.com/user-attachments/assets/17535790-e849-41b6-af0a-38db6f078390)
[BuildLog_2024_09_13_044911_Project_PhoenixPE.txt](https://github.com/user-attachments/files/16987006/BuildLog_2024_09_13_044911_Project_PhoenixPE.txt)

**Comment by homes32** [comment] 2024-09-14 03:20
[PhoenixPE Release 2024-09-13](https://github.com/PhoenixPE/PhoenixPE/releases/tag/2024.09.13) has been published and resolves the issues with spaces in the path and the Compress error.

**Comment by datacarecorp** [comment] 2024-09-18 02:40
Thanks a lot , All the Best for you & project.

**Closed** 2024-10-03 03:07 UTC
Labels: bug
