### ISSUE TITLE
Auto Login as Admin affects the function of PECMD System tray

### ISSUE THREAD

**Issue by VanFlusen** [PhoenixPE/PhoenixPE#49] opened 2023-05-19 13:13 UTC
I have enabled Auto Login as Admin.
When I click on the PECMD System tray, the Explorer opens for each function I select.

![2023-05-19 14 55 52](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/b6d7268a-d290-48c9-a3d1-0dc92d74070e)

**Comment by homes32** [comment] 2023-05-23 01:51
Sorry, I'm not able to reproduce this. Can you please post a SupportLog.zip (PhoenixPE dir > Logs) and give a description of your test environment?

**Comment by VanFlusen** [comment] 2023-05-24 10:05
Here is the hardware I used to build PhoenixPE:

![01](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/79104e05-8f95-4cf5-a3b2-6175cb6cffd0)

Operating System:

![02](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/c605a37d-cecc-4106-90dc-fa26be63a134)

PhoenixPE-2023.03.28-64 /  Win11 22H2 10.0.22621.525

I have a suspicion, please read Issue #23.
Is it possibly related to the network driver..
I had the host drivers installed to build PhoenixPe.

I boot the PE with Ventoy on AMD Ryzen PC:

![03](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/68a038fe-2312-4be6-b6aa-8ebe858185a9)
This phenomenon is new, but normalizes when I click on the taskbar.

I click on the PECMD task icon and hover the mouse over the options and immediately opens explorer.

![004](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/4389acfa-941f-412a-bbaa-405628e1198e)




[2023-05-24-1007-PhoenixPE-Logs.zip](https://github.com/PhoenixPE/PhoenixPE/files/11553226/2023-05-24-1007-PhoenixPE-Logs.zip)

**Comment by homes32** [comment] 2023-07-10 01:06
I'm able to confirm this issue affects multiple versions of PECMD.

**Comment by kevinwijnb** [comment] 2023-08-27 17:04
Any news on this?

**Comment by kevinwijnb** [comment] 2023-08-27 17:45
Just tried something and it seems to work:

I created a batch script with the command: 'taskkill /f /I'm explorer.exe' in it, and let it run through PECMD ini. Now I can switch resolutions with the PECMD menu and it doesn't show a new explorer window on boot!

Still need to test some more though..

**Comment by homes32** [comment] 2023-08-27 20:01
> Just tried something and it seems to work:
> 
> I created a batch script with the command: 'taskkill /f /I'm explorer.exe' in it, and let it run through PECMD ini. Now I can switch resolutions with the PECMD menu and it doesn't show a new explorer window on boot!
> 
> Still need to test some more though..

I do agree that the issue seems to be caused by PECMD spawning an additional explorer process with the admin session. The challange will be to create a solution that doesnt cause issues PhoenixPE's ability to switch back and forth between system and admin, if the user doesn't use the auto option and switches manually. Otherwise we are only solving half the problem killting explorer with the auto login, as we don't want to kill processes in a session the user might want to come back to.

Projects like win10XPE dont have this issue because once you switch to admin the system session is no longer available so its ok to kill off all the explorer processes.

**Comment by homes32** [comment] 2024-01-06 00:52
Resolved in 1c17ec77c3b58693a3330a88d21a0db8a5b8e76f

**Closed by homes32** 2024-01-06 00:52 UTC
